timeout: 10
wallpaper: boot():/wallpaper.png
term_background: FF000000
term_foreground: CCCCCC
interface_resolution: 1280x720
interface_branding_colour: 1
interface_help_hidden: no
interface_help_colour: 1
interface_branding: The Bleed Kernel (Limine 10.5.0)
editor_validation: no

/The Bleed Kernel
    protocol: limine
    path: boot():/boot/bleed-kernel
    MODULE_PATH=boot():/boot/initrd.tar
    resolution: 1280x720
    kaslr: yes
    cmdline: init=/initrd/bin/verdict

/Boot Options
//Feeble Mode (for Underpowered Machines)
    protocol: limine
    path: boot():/boot/bleed-kernel
    MODULE_PATH=boot():/boot/initrd.tar
    resolution: 960x540
    kaslr: no
    cmdline: init=/initrd/bin/verdict
//Verbose Mode (for Debugging)
    protocol: limine
    path: boot():/boot/bleed-kernel
    MODULE_PATH=boot():/boot/initrd.tar
    resolution: 1280x720
    kaslr: no
    cmdline: init=/initrd/bin/verdict verbose=yes